// web/app/pages/p/[slug].vue
<script setup lang="ts">
// import { PortableText } from '@portabletext/vue'
import ProjectHeader from '~/components/ProjectHeader.vue'
import { PROJECT_QUERY } from '~/lib/queries'
import type { Project, Seo } from '~/types/schema'
const route = useRoute()
const { data, refresh } = await useSanityQuery<Project>(PROJECT_QUERY, {
  slug: route.params.slug,
})

if (!data.value) {
  console.error('No data returned from Sanity query')
  throw createError({
    statusCode: 404,
    message: "Désolé la page demandée n'existe pas.",
  })
}

const pageData = data.value || ({} as Project)
const seo = pageData.seo || ({} as Seo)

useHead({
  title: seo?.metaTitle || 'Olivier Lellouche Design Workshop',
  meta: [{ name: 'description', content: seo?.metaDescription || '' }],
})
</script>

<template>
  <!-- <SmoothScroller> -->
  <div class="template template--project">
    <template v-if="data">
      <div class="mb-md">
        <ProjectHeader :input="data" />
      </div>
      <div class="images grid gap-sm md:gap-md">
        <div class="images__item" v-for="item in data.media" :key="item._key">
          <SanityImage :image="item" :alt="data.title" />
        </div>
      </div>
    </template>
    <div v-else>please edit page</div>
  </div>
  <!-- </SmoothScroller> -->
</template>

<style>
.template--project {
  /* margin-bottom: var(--spacing-lg); */
}
</style>

// web/src/app/(pages)/project/[slug]/page.tsx
import website from "@/app/config/website";
import { Project } from "@/app/types/schema";
import { getProject, projectQuery } from "@/app/utils/sanity-queries";
import { Metadata } from "next";
import React from "react";
import { draftMode } from "next/headers";
import { getClient } from "@/app/utils/sanity-client";
import PreJson from "@/app/components/ui/PreJson";
import SmoothScroller from "@/app/components/SmoothScroller";
import Figure from "@/app/components/ui/Figure";
import { PortableText } from "@portabletext/react";
import components from "@/app/utils/portableTextComponents";
import LivePeerPlayer from "@/app/components/ui/LivePeerPlayer";

type PageProps = {
  params: {
    slug: string;
  };
};

export async function generateMetadata({
  params,
}: PageProps): Promise<Metadata> {
  const data = await getProject(params.slug);
  return {
    title: data?.seo?.metaTitle || data.title,
    description: data?.seo?.metaDescription,
    openGraph: {
      images: data?.seo?.metaImage?.asset.url || website.image,
    },
  };
}

const Page: ({ params }: PageProps) => Promise<JSX.Element> = async ({
  params,
}) => {
  const { isEnabled: preview } = draftMode();
  let data: Project;
  if (preview) {
    data = await getClient({ token: process.env.SANITY_API_READ_TOKEN }).fetch(
      projectQuery,
      params
    );
  } else {
    data = (await getProject(params.slug)) as Project;
  }

  if (!data) return <div>please edit page</div>;
  // console.log(data);
  return (
    <div className='template--project '>
      {/* <PreJson input={data} /> */}
      {/* <div>{data.playbackId}</div> */}
      <SmoothScroller>
        {data.playbackId && (
          <div className='item shrink-0'>
            <LivePeerPlayer
              playbackId={data.playbackId}
              poster={data.coverImage?.asset.url}
            />
          </div>
        )}
        {data.coverImage && (
          <div className='item shrink-0'>
            <Figure image={data.coverImage} title={data.title} />
          </div>
        )}
      </SmoothScroller>
      <div className='footer fixed bottom-0 left-0 p-md'>
        <h1>{data.title}</h1>
        {data.body && (
          <PortableText value={data.body} components={components} />
        )}
      </div>
    </div>
  );
};

export default Page;
